### ISSUE TITLE
[Feature Request] Allow download

### ISSUE THREAD

**Issue by Synt3x** [ShaneIsrael/fireshare#112]
Would be great if there was a button that allowed the user to download the video clip.

**Comment by ShaneIsrael** [comment]
You can just right click the videos and choose "Save As".

**Comment by Synt3x** [comment]
Sure, but my friend is not that technical and it doesnt work on phone/tablets. But it's up to you if this is something you want to implement in your product. :)

**Comment by ShaneIsrael** [comment]
I wouldn't really call this a "technical" action.

Works on my phone (Android). You don't need to be technical to long press or right click a video. Since you can easily right click (or long press if on phone/tablet) the video and choose "Save As" I don't see the benefit of taking up additional UI space to add a button that does the same thing. 

Here it is working on my phone. 
![image](https://user-images.githubusercontent.com/1677199/183151885-aab3451e-255c-4dd6-8cf6-a479ba25ce73.png)

**Comment by Hukuma1** [comment]
+1 for this. I need to share quickly/privately some videos and need for the recipients to be able to download it. They're not exactly "Zoomers" so an option to show a dedicated download button would be an awesome feature for me as well.

Long-press on iOS doesn't work like on Android, I only get the option to save the poster.
