### ISSUE TITLE
IPs recorded in sqlite file

### ISSUE THREAD

**Issue by truthsword** [ShaneIsrael/fireshare#120]
Why are IPs recorded in the sqlite file? What is the source (some I don't recognize). This seems unnecessary, and a security concern. For example:

```
INSERT INTO "video_view" VALUES (1,'e7xxxxxxxxxxxxxxxxxxa2ceff4306287','107.150.23.212');
INSERT INTO "video_view" VALUES (2,'f13xxxxxxxxxxxxxxxxxx5c061e43c9fdd','161.129.70.14');
```
Thank you!

**Comment by ShaneIsrael** [comment]
It's required to track video views and for your own knowledge. In the future I plan on having a display so that you can see how many hits/views your getting from a particular source. This is not a security risk, this is no different than your reverse proxy spitting out the ip addresses of anybody connecting to your proxy to the logs.
