### ISSUE TITLE
Logging Error After Scan That Prevents Further Scanning

### ISSUE THREAD

**Issue by torrabsolute2** [ShaneIsrael/fireshare#128]
**Describe the bug**
Whether a manual library scan or a scheduled library scan, the cli shows "--- Logging error ---". I think that this keeps the scan process as currently active and prevents further scanning. 

**To Reproduce**
1. Manually scan or wait for the scehduled scan to begin
2. See error

**Screenshots**
https://imgur.com/rtJcq1C
![fireshare logging issue](https://user-images.githubusercontent.com/88910119/183799999-ae1d035c-d227-4258-a27e-05be8215ada7.png)

**Comment by torrabsolute2** [comment]
There was a folder in one of the directories that had a bunch of .jpgs in it. I deleted those and I think that mightve solved it? Unsure.

**Comment by ShaneIsrael** [comment]
Seems like the scan is error'ing while it tries to get video info for one of your videos. Might be that it's corrupt? Either way, because its breaking during the scan the lockfile isn't getting removed which is why subsequent scans are being aborted. it thinks the scan is still running when it's not. 

You can solve this by simply restarting the docker container and it will remove the lockfile on startup. However, it will probably keep breaking every time it tries to scan that video. 

You might want to inspect the video at /processed/video_links/21652*****.mp4 (its in your logs) Thats a simlink that fireshare creates to the actual video. I would try removing the actual video and the sim link and see if the scan works without issue. If so, its something about that video file in particular.

**Comment by torrabsolute2** [comment]
I looked and that folder that was deleted had emourmous video files in it as well. I just deleted it and everything is resolved! I can't dig into it more but im guessing this had a hard time with huge files.

**Comment by ShaneIsrael** [comment]
Depending the size that could definitely be the case. I've tested files in size up to about 30 gigabytes in size and haven't had an issue but I'm also running the software on a fairly beefy system.
