### ISSUE TITLE
look at the redlines and help me plz

### ISSUE THREAD

**Issue by yanquan2020** [ShaneIsrael/fireshare#131]
` <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

when i visit the website , the above redlines show up.
help me plz and i can't login either.

`An unknown error occurred while trying to log in`

**Comment by ShaneIsrael** [comment]
I just updated the demo site if thats what you are referring to, it should be working now. This issue should be fixed in the next version release.  If this is an issue with your own fireshare host, use the latest develop image for now. `shaneisrael/fireshare:develop`

**Comment by yanquan2020** [comment]
> I just updated the demo site if thats what you are referring to, it should be working now. This issue should be fixed in the next version release. If this is an issue with your own fireshare host, use the latest develop image for now. `shaneisrael/fireshare:develop`

thanks. it's my own host and i have solved the problem.

there's something  you might want to upgrade.

The delete funtion is not so good.When I want to delete the missing videos and error occurs and i had to delete the fireshare instance and create another one.

**Comment by ShaneIsrael** [comment]
Could you expand on what the error is? As far as I can tell the deletion works perfectly. If it is not working, it's likely a permission issue which would be something you'd need to look into on your system.

**Comment by yanquan2020** [comment]
i deleted one instance and i did not rm the old configuration fold or files.
when i create a new instance and use another videos fold path ,the old viedos still remains and shows missed on website.
so when i delete them,error occurs

**Comment by ShaneIsrael** [comment]
Fireshare still has your old video folder path in its database. You either have to delete them one at a time using fireshare which it will throw an error because the video files no longer exist since you're using a different path but it will remove their entries from the database. Or what **I would recommend doing is deleting the sqlite.db file from the fireshare data folder and restarting fireshare.** This will allow it to create a new database of your actual video directory you want to use.

Fireshare uses its database as the source of truth. If you change the volume mapping for your videos, or move/remove the videos manually Fireshare will still think they exist and will not automatically remove their entries from its database.
