### ISSUE TITLE
[Feature Request] Expiry date on videos uploaded by public

### ISSUE THREAD

**Issue by gogo199432** [ShaneIsrael/fireshare#135]
I want to self-host this but I'm afraid if the community I'm in starts using it, it will quickly eat up all my space. So it would be nice to be able to set an expiry date for videos. You can make this simple as anything uploaded by non-admin, would get a install-time defined expiry date.

**Comment by Shane-stage** [comment]
This is sorta outside the scope of what Fireshare is, which is a personal media share for yourself. Public upload is there so that there _is_ a way for others that are not you (such as a couple friends or family members) have a way to add their videos/clips. It was never meant to be a service used by an entire community. You start getting into the realm of what YouTube is and does.

It sounds like what you are looking for is something more akin to PeerTube. https://joinpeertube.org/
