### ISSUE TITLE
preview not appear in some application like mattermost

### ISSUE THREAD

**Issue by den13501** [ShaneIsrael/fireshare#146]
**Describe the bug**
Preview can show on discord, but cannot show on other application like mattermost, line chat room

**To Reproduce**
1. copy a link of a video, then paste link into channel of mattermost/line
2. compare to streamable video, it can show preview on mattermost/line

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/58270741/194883464-d59bb668-36fc-4769-878c-745d45aa7eb2.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]

**Additional context**

**Comment by ShaneIsrael** [comment]
As far as I know we have open graph support correctly in place, previews work on most applications (discord, slack, telegram, etc) that I’ve tried. I don’t have an easy way to test Line/Mattermost but I'm guessing they are not supporting Open Graph?

I won't be able to look into this until after this week since I'm out of town for work unfortunately.

**Comment by den13501** [comment]
Thank you, I love this project and I've just buy you a coffee yesterday, I am no hurry!

**Comment by ShaneIsrael** [comment]
I've looked into this a bit and can't seem to find any reason as to why fireshare metadata isn't being recognized on some sites. Will update if I come across potential solutions but for now I'm going to close this.
