### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Bat-Shark** [ShaneIsrael/fireshare#148]
Would love to know more about the performance requirements and setup. 

Is the model cpu or gpu bound? It sounds like there isn't any gpu transcoding or decoding going on during playback. 

For context, I have this spun up in a VM with pretty minimal resources, and it runs accordingly. Playback takes forever to get going and any changes cause significant waiting. I don't see much of a CPU spike but occasionally it's 100% but not consistently with playback issues. 

Is there a recommended hardware setup for this to run smoothly? Is the expectation that the files are also local to the playback docker vs a nas mount?

**Comment by ShaneIsrael** [comment]
Fireshare directly serves your videos as they are. The performance requirements should be fairly minimal but may increase depending on the size of your files. If you're files are massive in size it may require more cpu. 

You're mileage will vary. You may want to check that you have sufficient RAM available for the sizes of files you are serving. Also, playback will depend on the upload speed of the server that is hosting Fireshare. If you're VM is limiting upload traffic speed that could cause issues. The download speed of the client trying to watch your video also matters. 

It could be that the videos you are trying to serve are too large for the upload/download speeds you are able to work with.

**Comment by Bat-Shark** [comment]
Playback was via Firefox on the same LAN as the VM. So that's unlikely to be the issue but never know. I wonder if we could get a chart or something based on resolution to specs to upload that would be helpful to set performance expectations. 

Is the playback overhead in the client browser or on the server? Sounds like it loads the video into ram and then just serves that into the playback modal? Really depends on the original file size, my testing is with 2 to 5 minute shadowplay clips right now for example. 
3440x1440 at about 48000 kbps bitrate, 60 fps. That's about 1.7 gb so that would line up with maybe too big???

**Comment by ShaneIsrael** [comment]
The playback overhead should mostly be on the server. The entire video would not be loaded into memory however the individual chunks that are sent would be. This should not take up very much memory at all and should be the same amount of memory for every video regardless of the video size. 

If you want to attempt to make a chart based on resolution to specs be my guest but this is not something that I believe to be a worthwhile endeavor.

Have you tried running Fireshare outside of a VM and then comparing to it running inside a VM? If there is a noticeable difference then the root of the problem is likely either the settings of your VM or the hardware that your VM is running on.

If the bitrate of your video is 48000 kbps then you would need a consistent upload speed of 48mbps to serve that one video and a consistent download speed of at least 48mbps to watch it without playback issues.
