### ISSUE TITLE
Linuxserver.io / Swag support

### ISSUE THREAD

**Issue by rwtallant13** [ShaneIsrael/fireshare#155]
Have you considered reaching out to the linuxserver.io people to try and get an image for Fireshare put on their site? proper integration with SWAG without any messing around would be great.

**Comment by ShaneIsrael** [comment]
@rwtallant13 I have not, to me the benefit of swag is fairly insignificant since you can simply protect the service by setting it up behind a reverse proxy which is super simple and easy to do. The time that I do spend working on my projects I try to spend working directly on core features. I'm not against letting someone PR swag support if there was a good argument for having it and of course if somebody wanted to take the time to do it. 

Sorry if that wasn't the answer you were hoping for.
