### ISSUE TITLE
[Suggestion] Disable public feed entirely 

### ISSUE THREAD

**Issue by shulymn** [ShaneIsrael/fireshare#180]
Hello,

After a few hours trying to make fireshare work with authentik, I've given up.
So here I am posting a suggestion, it might as well be something everyone could use if it's accepted :

- An option to entirely disable the public feed, so no one could see the public videos list
- Going on the domain page (ex : v.fireshare.net) redirects to the login page
- Sending the video links (ex : https://v.fireshare.net/w/......) still works at it does now, but no access to the public feed from the sidebar.

That's all basically
Really good work otherwise, looking forward to integrated encoding as well ! 

Thank you

**Comment by ShaneIsrael** [comment]
I'm not quite sure what Authentik is, but as long as it supports deployment via docker containers it should work just fine. 

> An option to entirely disable the public feed, so no one could see the public videos list

This could be added, but I don't really see the point since you can keep your video privacy defaulted to "private". In which case, there would never be any videos on your public feed.

> Going on the domain page (ex : v.fireshare.net) redirects to the login page

If I decide to add in the option to completely disable the feed I would have the root take you to the login page in the event you are not currently logged in.

> Sending the video links (ex : https://v.fireshare.net/w/......) still works at it does now, but no access to the public feed from the sidebar.

Going to a direct /w/ link will show the public page on the sidebar.  (see screenshot)
![image](https://user-images.githubusercontent.com/1677199/231015236-5dd2cb90-d110-468d-8a8e-803a84125755.png)
