### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by dmserver** [ShaneIsrael/fireshare#183]
docker
1.2.8 

<html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>

**Comment by Shane-stage** [comment]
You are going to need to provide more details as to what you did to cause that error.

What is the url you are using to access? 
What does your docker-compose file look like? 
Is this happening on localhost or is it behind a reverse proxy? 

I can tell you right now the issue is not a bug in fireshare but is almost guaranteed to be an issue in how you set it up.

**Comment by ShaneIsrael** [comment]
You are going to need to provide more details as to what you did to cause that error.

What is the url you are using to access?
What does your docker-compose file look like?
Is this happening on localhost or is it behind a reverse proxy?

I can tell you right now the issue is not a bug in fireshare but is almost guaranteed to be an issue in how you set it up.
