### ISSUE TITLE
[Suggestion] Change the fireshare name on embed

### ISSUE THREAD

**Issue by RisedSky** [ShaneIsrael/fireshare#213]
I would like to change the fireshare name on the embed for discord  : 

![image](https://github.com/ShaneIsrael/fireshare/assets/23197999/0300f147-fa8e-4c4d-8846-e86ed8f3e25a)

**Comment by ShaneIsrael** [comment]
If it were a paid application I would be totally cool with building in that ability to change the "Fireshare" titling. But since it is a FOSS that titling is needed to give the tool exposure and direct other people to it and/or let them know what tool/app they are going to be directed to.

If you really care, is open source so I can't stop you if you want to fork the repo and create your own docker build with that changed for your own personal use if it really bothers you.

**Comment by RisedSky** [comment]
> If it were a paid application I would be totally cool with building in that ability to change the "Fireshare" titling. But since it is a FOSS that titling is needed to give the tool exposure and direct other people to it and/or let them know what tool/app they are going to be directed to.
> 
> If you really care, is open source so I can't stop you if you want to fork the repo and create your own docker build with that changed for your own personal use if it really bothers you.

Well, it does when it is in preview, else, i won't change the bottom left thing, only the titling.
The user will still be able to look at it and to find it, if he is interested of the project.
