### ISSUE TITLE
[QUESTION] Utilizing Intel iGPU

### ISSUE THREAD

**Issue by 7eventy7** [ShaneIsrael/fireshare#246]
I have read through the documentation but I did not find any mention of how to force Fireshare to utilize the iGPU on my i5-12400. I am currently having trouble hosting 1080p 60fps clips on the service and am limited to 720p. Please let me know if I'm missing something, or if this feature is not present.

**Comment by ShaneIsrael** [comment]
Fireshare does not at the moment support any form of transcoding. Fireshare serves videos as they are. Which means, you can't configure it to use your GPU since there's nothing for your gpu to do. It should use very little cpu even since its only serving your video and not transcoding or modifying it in any way. 

Hope that answers your question.

**Comment by ShaneIsrael** [comment]
If you are having trouble viewing your videos, then your videos may be too large and your upload speed may not be good enough to support the bitrate your videos are encoded at. If you are on your local network trying to watch videos but having issues, you maybe have an issue somewhere in your network thats limiting your transfer speeds.

**Comment by 7eventy7** [comment]
Thanks for the response!
