### ISSUE TITLE
[Feature request] Simple in-web video editing

### ISSUE THREAD

**Issue by Pheggas** [ShaneIsrael/fireshare#81]
Hello. I came across this project and really like it. In fact i was trying to find Streamable alternative for a long time. The only thing I miss compare to Streamable is video editing (mainly cropping). It would be super awesome if you could add it later and I would be grateful. Did you think about this feature?

**Comment by ShaneIsrael** [comment]
This is a feature we could possibly add but in a more virtual since. We don't really want to start with modifying any files right off the bat but could maybe create a "virtual" clip where you specify a start / end time which would create a new clip that you could link people too that only played the video between those time stamps. No modification to the source files would be done. 

IF we build something like this and it works well we could look into exporting those virtual clips as mp4 files.

These are both features that would take a decent amount of time and effort. A lot of UI would need to be made to do this well. So in short, it's a feature we would like to add but it may be a while before we get around to it. Keep checking back periodically.

**Comment by Pheggas** [comment]
Honestly, I didn't think about it from this perspective but I really like it. The way you suggested is really awesome as we wouldn't lose a single frame from that clip. I'm really hyped for this.

I really would contribute for this but unfortunately, i don't code often and even if, not in languages you use. Anyway, I'm really looking forward for it!

**Comment by ShaneIsrael** [comment]
Yep. There isn't an estimate on when such feature will make it in but it's something we have thought about. Don't expect it to be anytime soon. This is primarily a side project and there is a lot of stuff that still needs to be done.
