### ISSUE TITLE
Dev environment doesn't work as expected

### ISSUE THREAD

**Issue by AIndoria** [ShaneIsrael/fireshare#83]
**Describe the bug**
While 'running' the dev environment works (with some fiddles), the end result ends up in a window with a blue background and a bunch of XHR 404 errors.

**To Reproduce**

1. Clone git directory, go to root and run `bash ./run_local.sh`, wait for it to suceed to :5000
2. Open another terminal window, go to app/client and run `npm install` (or `npm install --legacy-deps`), followed by `npm start`. Gives a bunch of warnings, see the in the screenshot section (1).
3. Navigate to localhost:3000 (in this case, my homeserver 192.168.1.99:3000) to be greeted with the blue screen

**Expected behavior**
I expect it to run.

**Screenshots**
(1) The Warnings generated by npm install: 

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-side-effect@2.1.1
npm WARN Found: react@18.1.0
npm WARN node_modules/react
npm WARN   react@"^18.1.0" from the root project
npm WARN   20 more (@emotion/react, @emotion/styled, @mui/base, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.3.0 || ^17.0.0" from react-side-effect@2.1.1
npm WARN node_modules/react-side-effect
npm WARN   react-side-effect@"^2.1.0" from react-helmet@6.1.0
npm WARN   node_modules/react-helmet
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^16.3.0 || ^17.0.0" from react-side-effect@2.1.1
npm WARN   node_modules/react-side-effect
npm WARN     react-side-effect@"^2.1.0" from react-helmet@6.1.0
npm WARN     node_modules/react-helmet
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
```

What I see:

![image](https://user-images.githubusercontent.com/8932732/174494136-48e8198e-26a2-41f6-b589-6de0a1db384f.png)

What I see when I manually navigate to /#/login

![image](https://user-images.githubusercontent.com/8932732/174494164-d2789e18-490a-4a40-9876-dafc2f3ca0e6.png)

The errors on console:

![image](https://user-images.githubusercontent.com/8932732/174494169-3564a1b9-777d-4e04-88c8-dc95ea2ec7b9.png)

**Desktop (please complete the following information):**
 - Happens on every browser, Ubuntu 22.04 Server, Tried node 12.x and node 18.x

Am I missing something here?

**Comment by ShaneIsrael** [comment]
Why are you trying to navigate to it at 192.168.1.99:3000? That's why its not working, axios can't find the backend server because they run at localhost, not 192.168.... 

Follow the instructions, navigate to localhost:3000 which is where the FE lives and expects the BE which should be running at localhost:5000.

**Comment by AIndoria** [comment]
>Follow the instructions

Please read the issue again.

>Why are you trying to navigate to it at 192.168.1.99:3000?

Because BOTH the backend and the frontend are hosted at that server. I'm running BOTH on my homeserver, which is 192.168.1.99. Both are running there on localhost, on 3000 and 5000. It matters not whether I just ssh tunnel to my homeserver or just navigate to its IP.

**Comment by ShaneIsrael** [comment]
Okay, what you are doing is running it in development mode. Which does not work with how you are trying to run it. 

That is why the instructions specifically say to navigate to localhost:3000. It doesn't matter where you are running the BE or the FE if you are running it in development like you are. The FE and BE have to be accessed from the same machine they are running on via localhost. 

If you run it on some other computer even if its on the same network, it will not work. It sounds to me like you are trying to run it in development to use it rather than develop on it since you do not have experience with Docker.

**Comment by AIndoria** [comment]
>Okay, what you are doing is running it in development mode

Yes, I am aware.

> It sounds to me like you are trying to run it in development to use it rather than develop on it since you do not have experience with Docker.

I do have plenty of experience with docker, ty. I have a docker instance running already, but I needed some other stuff which I was going to see if I could ad. I was going to tinker with it, play around, see what I can add etc.

>If you run it on some other computer even if its on the same network, it will not work.

Interesting. 
 

If I run x on :5000 that has an IP of 1.2.3.4 and y on :3000 that has an ip of 1.2.3.4, are they not both unable to find each other using "localhost"?

**Comment by ShaneIsrael** [comment]
> If I run x on :5000 that has an IP of 1.2.3.4 and y on :3000 that has an ip of 1.2.3.4, are they not both unable to find each other using "localhost"?

Yes, because regardless of where the development servers are running, the web application is being loaded and run inside your browser. If you are on a different machine and accessing the web application it will generate an incorrect URL for the backend. 

The web app will look at your address: 192.168.x.x:3000 and see that its not localhost and assume since its not localhost it must be running in a production environment. So it will try to access the backend at 192.168.x.x/api/ which doesn't work because it needs to know the port.

If you were running it at localhost, the web app would see that its running at localhost and try to access the backend at localhost:5000. 

So the only way to use the application at an address like 192.168.x.x is if you run it in production mode where it's using nginx to proxy the traffic to the BE service running at localhost:5000. 

You could try to run it with nginx, see ./run_local_nginx.sh, but that's only experimental and I can't guarantee that will work. I have it there for a very specific test I was doing.

**Comment by AIndoria** [comment]
Interesting. Thank you.
